### ISSUE TITLE
ProgressBar 

### ISSUE THREAD

**Issue by di48l069** [di48l069/Flash-dl#13]
Re-sizing console causes progressbar to duplicate it self...

![progress](https://cloud.githubusercontent.com/assets/7794777/10876141/bdc38a58-8142-11e5-83bb-b5824b8b13ec.PNG)

**Comment by Kimmax** [comment]
Can't be fixed because of `Console. Write()`.
Maybe we should set fixed console size.

**Comment by di48l069** [comment]
:+1: Sounds good only a chop is going to re-size a console so just set a fixed size

**Comment by di48l069** [comment]
@Kimmax don't think its possible to set make width & height to console

**Comment by Kimmax** [comment]
no way to dedect or prevent this without digging into windows api
