### ISSUE TITLE
Repro Transfer

### ISSUE THREAD

**Issue by ghost** [di48l069/Flash-dl#16]
Hi @Kimmax Please remove Flash-dl from your side so I can transfer it over to you I no longer want part of it and besides 99% of the work is yours.

**Comment by Kimmax** [comment]
done

**Comment by ghost** [comment]
Transfer done I think you must accept.

**Comment by p1Ggy** [comment]
@Kimmax hello bud it’s Nico here I deleted my other account this is my new one. Was wondering can I have this repro transferred back to me? You have my number to confirm this is actually me.

**Comment by Kimmax** [comment]
done

**Comment by p1Ggy** [comment]
@Kimmax Hello, I have not received any notification for transfer.

**Comment by Kimmax** [comment]
Well, it's gone from my list soooooo..
You could fork mine

**Comment by Kimmax** [comment]
```Transfer ownership
This repository is being transferred to @p1Ggy.```
