### ISSUE TITLE
Command Handling

### ISSUE THREAD

**Issue by di48l069** [di48l069/Flash-dl#4]
<h3>Bugs & Features</h3>
- [x] Method names are a mess currently, need to fix that on the command caller
- [x] Have two different command files "DefaultCommand" and "Youtube" Default command must contain basic commands such as "clear", "quit" and "help"

**Comment by Kimmax** [comment]
There is no way to match against all playlist on YouTube because every user can add it to his own playlist(s). One possibility would be to match against the uploaders playlist, although that would coats many more API calls then now, so we need to check this out more later on.

**Comment by Kimmax** [comment]
Closed by next commit. Youtube commands should stay in default class as they would be called via Classname.Commands otherwise, which is bad.
